inherit_gem:
  rubocop-bsm:
    - default.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: "2.7"

Security/Open:
  Exclude:
    - "core/lib/bfs/bucket/abstract.rb"
    - "core/lib/bfs/blob.rb"
Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
